//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.DataBaseBuses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buses
    {
        public Buses()
        {
            this.Flights = new HashSet<Flights>();
            this.Seats = new HashSet<Seats>();
        }
    
        public int BusId { get; set; }
        public string BusName { get; set; }
        public int CountSeats { get; set; }
        public string Information { get; set; }
    
        public virtual ICollection<Flights> Flights { get; set; }
        public virtual ICollection<Seats> Seats { get; set; }
    }
}
