//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.DataBaseBuses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public Cities()
        {
            this.Flights = new HashSet<Flights>();
            this.Flights1 = new HashSet<Flights>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public string Information { get; set; }
    
        public virtual ICollection<Flights> Flights { get; set; }
        public virtual ICollection<Flights> Flights1 { get; set; }
    }
}
