//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.DataBaseBuses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public Flights()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int FlightId { get; set; }
        public string FlightNumber { get; set; }
        public int CityIdStart { get; set; }
        public int CityIdEnd { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.TimeSpan ArrivaTime { get; set; }
        public int BusId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Cities Cities1 { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
