//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.DataBaseBuses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int FlightId { get; set; }
        public int SeatId { get; set; }
        public int DiscountId { get; set; }
        public Nullable<bool> Sold { get; set; }
        public Nullable<bool> Reserve { get; set; }
        public Nullable<bool> Canceled { get; set; }
    
        public virtual Discounts Discounts { get; set; }
        public virtual Flights Flights { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
